## 09-10: Generazione campioni da distribuzione scelta

In [1]:
from scipy.stats import multinomial, dirichlet
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Multinomiale

In [2]:
n_cat = 4
supp = np.random.randint(0,n_cat, size=1000)
uniques, p = np.unique(supp,return_counts=True)
p = p / supp.size
p = np.round(p, 3)
print(p)

[0.248 0.234 0.263 0.255]


In [3]:
n_trials = 20
gen = multinomial.rvs(n_trials, p, size=1000)
gen

array([[3, 3, 7, 7],
       [9, 4, 2, 5],
       [5, 4, 6, 5],
       ...,
       [5, 5, 2, 8],
       [6, 6, 5, 3],
       [3, 7, 2, 8]], shape=(1000, 4))

In [4]:
estimated_p = gen.mean(axis=0) / n_trials
estimated_p = np.round(estimated_p, 3)
print(estimated_p)

[0.25  0.233 0.266 0.251]


## Dirichlet

In [5]:
samples = np.random.randint(1,6, size=3)
samples

array([1, 3, 4])

In [6]:
gen = dirichlet.rvs(samples, size=4)
gen

array([[0.17879651, 0.3029195 , 0.518284  ],
       [0.02026829, 0.26864503, 0.71108669],
       [0.12360091, 0.54761409, 0.328785  ],
       [0.05088434, 0.40458376, 0.54453189]])